owner: dlsudatasci
repo: digital-office-status

sites:
  - name: Digital office server
    url: https://wa.altdsi.com
  - name: Hosted map assets
    url: http://altdsi.com/workadventure-digital-office/

status-website:
  cname: "" # Leave this blank unless you want a custom domain for the status page
  logoUrl: 1000000000 # You can paste an image URL here later for your org logo
  name: Digital Office Status
  introTitle: "**Live Server Monitoring**"
  introMessage: This page tracks the real-time status of our virtual office.
  theme: dark
